# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecaNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DecaNews
    pod 'SwiftLint'
    pod 'GoogleSignIn', '~> 5.0'
end
